from pathlib import Path
import shutil
import tempfile
import unittest

import yaml

from scripts.apm_smoke import require_runner, validate_deployment


class DeliveryTests(unittest.TestCase):
    def setUp(self):
        temporary = tempfile.TemporaryDirectory()
        self.addCleanup(temporary.cleanup)
        self.root = Path(temporary.name)
        self.source, self.scope = self.root / 'source', self.root / 'scope'
        self.sha = 'a' * 40
        files = {
            'skills/sample/SKILL.md': '---\nname: sample\ndescription: Example.\n---\n# Sample\n',
            'skills/sample/asset.txt': 'payload',
            '.apm/instructions/core.instructions.md': '---\ntype: Instruction\ntitle: Core\ndescription: Core.\n---\n## Core\n\nKeep work safe.\n',
        }
        for name, text in files.items():
            path = self.source / name
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding='utf-8')
        self.cached = self.scope / '.apm/apm_modules/daiksud/agents'
        shutil.copytree(self.source, self.cached)
        shutil.copytree(self.source / 'skills', self.scope / '.agents/skills')
        for target in ('codex', 'copilot'):
            path = self.scope / f'.{target}/AGENTS.md'
            path.parent.mkdir()
            path.write_text('<!-- Generated by APM CLI -->\n## Core\n\nKeep work safe.\n', encoding='utf-8')
        self.lock = self.scope / '.apm/apm.lock.yaml'
        self.lock.write_text(yaml.safe_dump({'dependencies': [
            {'repo_url': 'daiksud/agents', 'resolved_commit': self.sha}]}), encoding='utf-8')

    def validate(self):
        return validate_deployment(self.source, self.scope, self.sha)

    def test_complete_deployment_and_missing_asset(self):
        self.assertEqual([], self.validate())
        (self.scope / '.agents/skills/sample/asset.txt').unlink()
        self.assertTrue(self.validate())

    def test_cached_and_deployed_content_must_match_candidate(self):
        for path in [self.cached / 'skills/sample/asset.txt',
                     self.scope / '.agents/skills/sample/SKILL.md',
                     self.scope / '.codex/AGENTS.md']:
            with self.subTest(path=path):
                original = path.read_bytes()
                path.write_text('stale or handwritten content', encoding='utf-8')
                self.assertTrue(self.validate())
                path.write_bytes(original)

    def test_rewritten_outbound_link_resolves_to_same_cached_source(self):
        for root in (self.source, self.cached):
            target = root / 'docs/help.md'
            target.parent.mkdir()
            target.write_text('Help', encoding='utf-8')
            skill = root / 'skills/sample/SKILL.md'
            skill.write_text(skill.read_text() + '\n[Help](../../docs/help.md)\n', encoding='utf-8')
        deployed = self.scope / '.agents/skills/sample/SKILL.md'
        deployed.write_text(deployed.read_text() +
                           '\n[Help](../../../.apm/apm_modules/daiksud/agents/docs/help.md)\n', encoding='utf-8')
        self.assertEqual([], self.validate())
        (self.cached / 'docs/help.md').write_text('wrong document', encoding='utf-8')
        self.assertTrue(self.validate())

    def test_obsolete_owned_skill_is_rejected(self):
        obsolete = self.scope / '.agents/skills/obsolete/SKILL.md'
        obsolete.parent.mkdir()
        obsolete.write_text('old skill', encoding='utf-8')
        self.assertTrue(self.validate())

    def test_wrong_commit_is_rejected(self):
        self.assertTrue(validate_deployment(self.source, self.scope, 'b' * 40))

    def test_only_empty_disposable_runner_scope_is_accepted(self):
        empty = self.root / 'empty'
        env = {'GITHUB_ACTIONS': 'true', 'RUNNER_ENVIRONMENT': 'github-hosted'}
        require_runner(env, empty)
        for environment, scope in [({}, empty), (env, self.scope)]:
            with self.subTest(environment=environment):
                with self.assertRaises(RuntimeError):
                    require_runner(environment, scope)
