from pathlib import Path
import shutil
import os
import subprocess
import tempfile
import unittest

import yaml

from scripts.apm_smoke import candidate_environment, require_runner, require_same, snapshot, validate_deployment


class DeliveryTests(unittest.TestCase):
    def setUp(self):
        temporary = tempfile.TemporaryDirectory()
        self.addCleanup(temporary.cleanup)
        self.root = Path(temporary.name)
        self.source, self.scope = self.root / 'source', self.root / 'scope'
        self.sha = 'a' * 40
        files = {
            'skills/sample/SKILL.md': '---\nname: sample\ndescription: Example.\n---\n# Sample\n',
            'skills/sample/asset.txt': 'payload',
            '.apm/instructions/core.instructions.md': '---\ntype: Instruction\ntitle: Core\ndescription: Core.\n---\n## Core\n\nKeep work safe.\n',
        }
        for name, text in files.items():
            path = self.source / name
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding='utf-8')
        self.cached = self.scope / '.apm/apm_modules/daiksud/agents'
        shutil.copytree(self.source, self.cached)
        shutil.copytree(self.source / 'skills', self.scope / '.agents/skills')
        for target in ('codex', 'copilot'):
            path = self.scope / f'.{target}/AGENTS.md'
            path.parent.mkdir()
            path.write_text('<!-- Generated by APM CLI -->\n## Core\n\nKeep work safe.\n', encoding='utf-8')
        self.lock = self.scope / '.apm/apm.lock.yaml'
        self.lock.write_text(yaml.safe_dump({'dependencies': [
            {'repo_url': 'daiksud/agents', 'resolved_commit': self.sha}]}), encoding='utf-8')

    def validate(self):
        return validate_deployment(self.source, self.scope, self.sha)

    def test_complete_deployment_and_missing_asset(self):
        self.assertEqual([], self.validate())
        (self.scope / '.agents/skills/sample/asset.txt').unlink()
        self.assertTrue(self.validate())

    def test_cached_and_deployed_content_must_match_candidate(self):
        for path in [self.cached / 'skills/sample/asset.txt',
                     self.scope / '.agents/skills/sample/SKILL.md',
                     self.scope / '.codex/AGENTS.md']:
            with self.subTest(path=path):
                original = path.read_bytes()
                path.write_text('stale or handwritten content', encoding='utf-8')
                self.assertTrue(self.validate())
                path.write_bytes(original)

    def test_rewritten_outbound_link_resolves_to_same_cached_source(self):
        for root in (self.source, self.cached):
            target = root / 'docs/help.md'
            target.parent.mkdir()
            target.write_text('Help', encoding='utf-8')
            skill = root / 'skills/sample/SKILL.md'
            skill.write_text(skill.read_text() + '\n[Help](../../docs/help.md)\n', encoding='utf-8')
        deployed = self.scope / '.agents/skills/sample/SKILL.md'
        deployed.write_text(deployed.read_text() +
                           '\n[Help](../../../.apm/apm_modules/daiksud/agents/docs/help.md)\n', encoding='utf-8')
        self.assertEqual([], self.validate())
        (self.cached / 'docs/help.md').write_text('wrong document', encoding='utf-8')
        self.assertTrue(self.validate())

    def test_obsolete_owned_skill_is_rejected(self):
        obsolete = self.scope / '.agents/skills/obsolete/SKILL.md'
        obsolete.parent.mkdir()
        obsolete.write_text('old skill', encoding='utf-8')
        self.assertTrue(self.validate())

    def test_snapshot_detects_generated_and_skill_changes(self):
        before = snapshot(self.scope)
        self.assertIn('.codex/AGENTS.md', before)
        self.assertIn('.agents/skills/sample/asset.txt', before)
        require_same(before, snapshot(self.scope), 'reinstall')
        (self.scope / '.codex/AGENTS.md').write_text('handwritten changed', encoding='utf-8')
        with self.assertRaises(RuntimeError):
            require_same(before, snapshot(self.scope), 'handwritten protection')

    def test_candidate_mirror_serves_exact_commit_without_network(self):
        subprocess.run(['git', 'init', '-q', str(self.source)], check=True)
        subprocess.run(['git', '-C', str(self.source), 'add', '.'], check=True)
        subprocess.run(['git', '-C', str(self.source), '-c', 'user.name=Fixture',
                        '-c', 'user.email=fixture@example.invalid', 'commit', '-qm', 'fixture'], check=True)
        subprocess.run(['git', '-C', str(self.source), 'checkout', '--detach', '-q'], check=True)
        subprocess.run(['git', '-C', str(self.source), '-c', 'user.name=Fixture',
                        '-c', 'user.email=fixture@example.invalid', 'commit', '--allow-empty', '-qm', 'candidate'], check=True)
        sha = subprocess.check_output(['git', '-C', str(self.source), 'rev-parse', 'HEAD']).decode().strip()
        environment = candidate_environment(self.source, self.root / 'mirror.git')
        self.assertIn('GIT_CONFIG_COUNT', environment)
        result = subprocess.check_output(['git', 'ls-remote', 'https://github.com/daiksud/agents.git', 'HEAD'],
                                         env={**os.environ, **environment, 'GIT_ALLOW_PROTOCOL': 'file'})
        self.assertEqual(sha, result.decode().split()[0])

    def test_missing_instruction_frontmatter_is_a_validation_error(self):
        for root in (self.source, self.cached):
            (root / '.apm/instructions/core.instructions.md').write_text('Missing metadata', encoding='utf-8')
        self.assertTrue(self.validate())

    def test_wrong_commit_is_rejected(self):
        self.assertTrue(validate_deployment(self.source, self.scope, 'b' * 40))

    def test_only_empty_disposable_runner_scope_is_accepted(self):
        empty = self.root / 'empty'
        env = {'GITHUB_ACTIONS': 'true', 'RUNNER_ENVIRONMENT': 'github-hosted'}
        require_runner(env, empty)
        for environment, scope in [({}, empty), (env, self.scope)]:
            with self.subTest(environment=environment):
                with self.assertRaises(RuntimeError):
                    require_runner(environment, scope)
