# Common configuration based on GitHub rendering.
[global]
disable = ["MD013", "MD033", "MD034", "MD041"]

[MD060]
enabled = true
style = "compact"

[MD076]
style = "tight"
allow-loose-continuation = true
