"""Verify APM delivery only on disposable GitHub-hosted runners."""
from pathlib import Path
import hashlib
import os
import re

import yaml


def expected_content(original, source, cached, deployed, skill_root):
    if original.suffix != '.md':
        return original.read_bytes()

    def rewrite(match):
        link, marker, fragment = match[1].partition('#')
        if not link or ':' in link or link.startswith('/'):
            return match[0]
        target = (original.parent / link).resolve()
        if target.is_relative_to(skill_root):
            return match[0]
        cached_target = cached / target.relative_to(source)
        if target.read_bytes() != cached_target.read_bytes():
            raise ValueError(f'outbound link target differs: {link}')
        return '](' + os.path.relpath(cached_target, deployed.parent) + marker + fragment + ')'

    return re.sub(r'\]\(([^)\s]+)\)', rewrite, original.read_text(encoding='utf-8')).encode('utf-8')


def validate_deployment(source, scope, sha):
    source, scope = source.resolve(), scope.resolve()
    errors = []
    cached = scope / '.apm/apm_modules/daiksud/agents'
    try:
        lock = yaml.safe_load((scope / '.apm/apm.lock.yaml').read_text(encoding='utf-8'))
        if not any(d.get('repo_url') == 'daiksud/agents' and d.get('resolved_commit') == sha
                   for d in lock['dependencies']):
            errors.append('installed commit differs from candidate')
        skills = sorted((source / 'skills').glob('*/SKILL.md'))
        if not skills:
            errors.append('candidate contains no skills')
        installed = {p.parent.name for p in (scope / '.agents/skills').glob('*/SKILL.md')}
        if installed - {p.parent.name for p in skills} - {'skill-creator'}:
            errors.append('obsolete or unexpected deployed skills')
        for skill in skills:
            for original in sorted(skill.parent.rglob('*')):
                if not original.is_file():
                    continue
                relative = original.relative_to(source)
                if (cached / relative).read_bytes() != original.read_bytes():
                    errors.append(f'cached candidate differs: {relative}')
                deployed = scope / '.agents' / relative
                if deployed.read_bytes() != expected_content(original, source, cached, deployed, skill.parent):
                    errors.append(f'deployed content differs: {relative}')
        core = Path('.apm/instructions/core.instructions.md')
        original = (source / core).read_text(encoding='utf-8')
        if (cached / core).read_text(encoding='utf-8') != original:
            errors.append('cached instructions differ')
        body = original.split('---', 2)[2].strip()
        for target in ('codex', 'copilot'):
            generated = (scope / f'.{target}/AGENTS.md').read_text(encoding='utf-8')
            if 'Generated by APM CLI' not in generated or body not in generated:
                errors.append(f'{target} instructions were not generated from candidate')
    except (OSError, ValueError, KeyError, TypeError, yaml.YAMLError) as error:
        errors.append(str(error))
    return errors


def require_runner(environment, scope):
    if (environment.get('GITHUB_ACTIONS') != 'true'
            or environment.get('RUNNER_ENVIRONMENT') != 'github-hosted'):
        raise RuntimeError('APM global smoke test requires a disposable GitHub-hosted runner')
    if any((scope / name).exists() for name in
           ('.apm', '.agents/skills', '.codex/AGENTS.md', '.copilot/AGENTS.md')):
        raise RuntimeError('Refusing to modify an existing user installation')


def snapshot(scope):
    files = list((scope / '.agents/skills').rglob('*'))
    files += [scope / f'.{target}/AGENTS.md' for target in ('codex', 'copilot')]
    return {str(path.relative_to(scope)): hashlib.sha256(path.read_bytes()).hexdigest()
            for path in sorted(files) if path.is_file()}


def require_same(before, after, label):
    if before != after:
        raise RuntimeError(f'{label}: files changed unexpectedly')


def candidate_environment(source, directory):
    import subprocess

    subprocess.run(['git', 'clone', '--mirror', str(source), str(directory)], check=True, timeout=60)
    sha = subprocess.check_output(['git', '-C', str(source), 'rev-parse', 'HEAD'], text=True).strip()
    subprocess.run(['git', '-C', str(directory), 'update-ref', 'refs/heads/ci-candidate', sha], check=True)
    subprocess.run(['git', '-C', str(directory), 'symbolic-ref', 'HEAD', 'refs/heads/ci-candidate'], check=True)
    offset = int(os.environ.get('GIT_CONFIG_COUNT', '0'))
    environment = {'GIT_CONFIG_COUNT': str(offset + 2)}
    for index, suffix in enumerate(('.git', '')):
        environment[f'GIT_CONFIG_KEY_{offset + index}'] = f'url.{directory.resolve().as_uri()}.insteadOf'
        environment[f'GIT_CONFIG_VALUE_{offset + index}'] = 'https://github.com/daiksud/agents' + suffix
    return environment


def main():
    import io
    import json
    import platform
    import subprocess
    import tarfile
    import tempfile
    import time

    source, scope = Path(__file__).resolve().parents[1], Path.home()
    require_runner(os.environ, scope)
    config = json.loads((source / '.github/delivery.json').read_text())
    candidate = subprocess.check_output(['git', 'rev-parse', 'HEAD'], cwd=source).decode().strip()
    baseline = config['baseline_sha']
    if not all(re.fullmatch('[0-9a-f]{40}', sha) for sha in (candidate, baseline)):
        raise RuntimeError('Delivery requires immutable commit SHAs')
    report = {'candidate': candidate, 'baseline': baseline, 'environment': platform.platform(),
              'python': platform.python_version(), 'phases': {}}
    report_path = Path(os.environ['RUNNER_TEMP']) / 'delivery-report.json'
    started = time.monotonic()
    process_environment = os.environ.copy()
    report['source_transport'] = 'public-github'

    def run(*arguments):
        print('+', ' '.join(arguments), flush=True)
        subprocess.run(arguments, cwd=source, check=True, stdin=subprocess.DEVNULL, timeout=180,
                       env=process_environment)

    def compile_and_verify(tree, sha, phase):
        run('apm', 'compile', '--global', '--dry-run')
        run('apm', 'compile', '--global')
        errors = validate_deployment(tree, scope, sha)
        if errors:
            raise RuntimeError('\n'.join(errors))
        lock = yaml.safe_load((scope / '.apm/apm.lock.yaml').read_text())
        dependencies = [{k: d.get(k) for k in ('repo_url', 'resolved_commit', 'virtual_path')}
                        for d in lock['dependencies']]
        if sha == candidate and not any(
                d['resolved_commit'] == config['skill_creator_sha']
                and d['virtual_path'] == 'skills/skill-creator' for d in dependencies):
            raise RuntimeError('skill-creator dependency does not match its pin')
        if not (scope / '.agents/skills/skill-creator/SKILL.md').is_file():
            raise RuntimeError('skill-creator was not deployed')
        hashes = snapshot(scope)
        report['phases'][phase] = {'sha': sha, 'hashes': hashes, 'dependencies': dependencies,
                                  'elapsed_seconds': round(time.monotonic() - started, 2)}
        return hashes

    try:
        for tool in ('apm', 'gh'):
            report[tool] = subprocess.check_output([tool, '--version'], text=True).strip()
        with tempfile.TemporaryDirectory(prefix='agents-baseline-') as directory:
            old_source = Path(directory)
            archive = subprocess.check_output(['git', 'archive', baseline], cwd=source)
            with tarfile.open(fileobj=io.BytesIO(archive)) as bundle:
                bundle.extractall(old_source, filter='data')
            if os.environ.get('GITHUB_EVENT_NAME') == 'pull_request':
                process_environment.update(candidate_environment(source, old_source / 'origin.git'))
                report['source_transport'] = 'local-mirror-of-integration-candidate'
            handwritten = {}
            for target in ('codex', 'copilot'):
                path = scope / f'.{target}/AGENTS.md'
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(f'Handwritten {target} instructions.\n', encoding='utf-8')
                handwritten[path] = path.read_bytes()
            run('apm', 'install', '--global', '--target', 'codex,copilot', f'daiksud/agents#{candidate}')
            run('apm', 'compile', '--global', '--dry-run')
            run('apm', 'compile', '--global')
            require_same(handwritten, {p: p.read_bytes() for p in handwritten}, 'handwritten protection')
            report['handwritten_preserved'] = True
            for path in handwritten:
                path.unlink()  # Only these verified, test-created files are removed.
            clean = compile_and_verify(source, candidate, 'clean')
            run('apm', 'install', '--global', '--frozen')
            require_same(clean, compile_and_verify(source, candidate, 'reinstall'), 'reinstall')
            run('apm', 'install', '--global', '--target', 'codex,copilot', f'daiksud/agents#{baseline}')
            previous = compile_and_verify(old_source, baseline, 'baseline')
            manifest = scope / '.apm/apm.yml'
            data = yaml.safe_load(manifest.read_text())
            data['dependencies']['apm'] = [
                f'daiksud/agents#{candidate}' if d == f'daiksud/agents#{baseline}' else d
                for d in data['dependencies']['apm']]
            manifest.write_text(yaml.safe_dump(data), encoding='utf-8')
            run('apm', 'update', '--global', '--yes', 'daiksud/agents')
            run('apm', 'install', '--global')
            require_same(clean, compile_and_verify(source, candidate, 'update'), 'update')
            restoring = time.monotonic()
            run('apm', 'install', '--global', '--target', 'codex,copilot', f'daiksud/agents#{baseline}')
            require_same(previous, compile_and_verify(old_source, baseline, 'restore'), 'restore')
            report['restore_seconds'] = round(time.monotonic() - restoring, 2)
            if report['restore_seconds'] > 600:
                raise RuntimeError('Restoration exceeded the initial 10-minute target')
            report['success'] = True
    finally:
        report['elapsed_seconds'] = round(time.monotonic() - started, 2)
        report_path.write_text(json.dumps(report, indent=2) + '\n', encoding='utf-8')
        print(f'Delivery evidence: {report_path}', flush=True)


if __name__ == '__main__':
    main()
