"""Verify APM delivery only on disposable GitHub-hosted runners."""
from pathlib import Path

import yaml


def validate_deployment(source, scope, sha):
    errors = []
    cached = scope / '.apm/apm_modules/daiksud/agents'
    try:
        lock = yaml.safe_load((scope / '.apm/apm.lock.yaml').read_text(encoding='utf-8'))
        if not any(d.get('repo_url') == 'daiksud/agents' and d.get('resolved_commit') == sha
                   for d in lock['dependencies']):
            errors.append('installed commit differs from candidate')
        skills = sorted((source / 'skills').glob('*/SKILL.md'))
        if not skills:
            errors.append('candidate contains no skills')
        for skill in skills:
            for original in sorted(skill.parent.rglob('*')):
                if not original.is_file():
                    continue
                relative = original.relative_to(source)
                if (cached / relative).read_bytes() != original.read_bytes():
                    errors.append(f'cached candidate differs: {relative}')
                deployed = scope / '.agents' / relative
                if deployed.read_bytes() != original.read_bytes():
                    errors.append(f'deployed content differs: {relative}')
        core = Path('.apm/instructions/core.instructions.md')
        original = (source / core).read_text(encoding='utf-8')
        if (cached / core).read_text(encoding='utf-8') != original:
            errors.append('cached instructions differ')
        body = original.split('---', 2)[2].strip()
        for target in ('codex', 'copilot'):
            generated = (scope / f'.{target}/AGENTS.md').read_text(encoding='utf-8')
            if 'Generated by APM CLI' not in generated or body not in generated:
                errors.append(f'{target} instructions were not generated from candidate')
    except (OSError, ValueError, KeyError, TypeError, yaml.YAMLError) as error:
        errors.append(str(error))
    return errors


def require_runner(environment, scope):
    if (environment.get('GITHUB_ACTIONS') != 'true'
            or environment.get('RUNNER_ENVIRONMENT') != 'github-hosted'):
        raise RuntimeError('APM global smoke test requires a disposable GitHub-hosted runner')
    if any((scope / name).exists() for name in
           ('.apm', '.agents/skills', '.codex/AGENTS.md', '.copilot/AGENTS.md')):
        raise RuntimeError('Refusing to modify an existing user installation')
